### ISSUE TITLE
测试的问题

### ISSUE THREAD

**Issue by CptBreeza** [GreenNerd/ChineseHolidays#1]
`ChineseHolidays` 缓存 `json` 数据文件到了本地，导致的问题：
如果已经使用过 `ChineseHolidays` 了的话，运行测试时 stub `ChineseHolidays` 的请求便无效，因为它不会再次请求，而是会使用本地的文件缓存。

**Comment by hw676018683** [comment]
没懂啊，是测试挂了吗

**Comment by CptBreeza** [comment]
在测试的时候，我想要 ChineseHolidays  使用我伪造的 holidays，现在的话，无法通过 stub 请求实现？

**Comment by hw676018683** [comment]
加了一个删除缓存的方法`ChineseHolidays.remove_local_cache`，你看下

**Comment by CptBreeza** [comment]
好的
